apiVersion: v1
kind: Service
metadata:
  name: resumeai-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backEnd.containerPort }}
      targetPort: {{ .Values.backEnd.containerPort }}
  selector:
    app: resumeai-backend
