apiVersion: v1
kind: Service
metadata:
  name: resumeai-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontEnd.containerPort }}
      targetPort: {{ .Values.frontEnd.containerPort }}
  selector:
    app: resumeai-frontend