apiVersion: v1
kind: Secret
metadata:
  name: resumeai-secrets
type: Opaque
data:
  MONGO_URL: {{ .Values.secrets.mongoUrl | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  OPENAI_KEY: {{ .Values.secrets.openAiKey | b64enc | quote }}
  GMAIL_USER: {{ .Values.secrets.gmailUser | b64enc | quote }}
  GMAIL_PASS: {{ .Values.secrets.gmailPass | b64enc | quote }}